# Generated by Django 3.0.3 on 2020-02-16 18:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[users.models.username_validator])),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid McGill email address', whitelist=['gmail.com', 'mcgill.ca'])])),
                ('privilege', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RegularUser',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[users.models.username_validator])),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid McGill email address', whitelist=['gmail.com', 'mcgill.ca'])])),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('rating_avg', models.DecimalField(decimal_places=2, max_digits=3, validators=[users.models.user_rating_validator])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('regularuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.RegularUser')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.regularuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('regularuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.RegularUser')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('faculty', models.CharField(blank=True, choices=[('AGR', 'Faculty of Agricultural and Environmental Sciences'), ('ART', 'Faculty of Arts'), ('CNT', 'School of Continuing Studies'), ('DNT', 'Faculty of Dentistry'), ('EDU', 'Faculty of Education'), ('ENG', 'Faculty of Engineering'), ('GRD', 'Graduate and Postdoctoral Studies'), ('LAW', 'Faculty of Law'), ('MNG', 'Desautels Faculty of Management'), ('MED', 'Faculty of Medicine'), ('MUS', 'Schulich School of Music'), ('SCI', 'Faculty of Science'), ('ALU', 'Alumni')], max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.regularuser',),
        ),
        migrations.CreateModel(
            name='UserFlag',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('details', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 'Rating One'), (2, 'Rating Two'), (3, 'Rating Three'), (4, 'Rating Four'), (5, 'Rating Five')])),
                ('comment', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Student')),
            ],
        ),
    ]
