# Generated by Django 3.0.4 on 2020-03-09 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('privilege', models.CharField(choices=[('A', 'Admin'), ('U', 'Regular User'), ('P', 'Pending verification'), ('L', 'Locked user')], max_length=1)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegularUser',
            fields=[
                ('privilege', models.CharField(choices=[('A', 'Admin'), ('U', 'Regular User'), ('P', 'Pending verification'), ('L', 'Locked user')], max_length=1)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('regularuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.RegularUser')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.regularuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('regularuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.RegularUser')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('faculty', models.CharField(blank=True, choices=[('AGR', 'Faculty of Agricultural and Environmental Sciences'), ('ART', 'Faculty of Arts'), ('CNT', 'School of Continuing Studies'), ('DNT', 'Faculty of Dentistry'), ('EDU', 'Faculty of Education'), ('ENG', 'Faculty of Engineering'), ('GRD', 'Graduate and Postdoctoral Studies'), ('LAW', 'Faculty of Law'), ('MNG', 'Desautels Faculty of Management'), ('MED', 'Faculty of Medicine'), ('MUS', 'Schulich School of Music'), ('SCI', 'Faculty of Science'), ('ALU', 'Alumni')], max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.regularuser',),
        ),
    ]
