# Generated by Django 3.0.2 on 2020-01-31 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid McGill email address', whitelist=['gmail.com', 'mcgill.ca'])]),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid McGill email address', whitelist=['gmail.com', 'mcgill.ca'])]),
        ),
    ]
