# Generated by Django 3.0.3 on 2020-02-16 05:11

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200216_0011'),
        ('users', '0004_auto_20200131_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='regularuser',
            name='privilege',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'Regular User')], default=datetime.datetime(2020, 2, 16, 5, 10, 58, 75267, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userflag',
            name='event',
            field=models.ForeignKey(default=datetime.datetime(2020, 2, 16, 5, 11, 6, 113154, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='author', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userflag',
            name='recepient',
            field=models.ForeignKey(default=datetime.datetime(2020, 2, 16, 5, 11, 18, 646897, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='recepient', to='users.RegularUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid McGill email address', whitelist=['mail.mcgill.camcgill.ca'])]),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='privilege',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'Regular User')], max_length=1),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid McGill email address', whitelist=['mail.mcgill.camcgill.ca'])]),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), to='users.Student'),
        ),
        migrations.AlterField(
            model_name='userflag',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), to='users.Student'),
        ),
    ]
