# Generated by Django 3.0.4 on 2020-03-09 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
                ('postalcode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('datetime', models.DateField()),
                ('fee', models.DecimalField(decimal_places=3, default=0, max_digits=1000)),
                ('max_capacity', models.PositiveSmallIntegerField()),
                ('min_capacity', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('OUT', 'Outdoor events'), ('GAM', 'Games')], max_length=3)),
                ('address', models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Address')),
                ('attendees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
