# Generated by Django 3.0.2 on 2020-02-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Address'),
        ),
    ]