# Generated by Django 3.0.2 on 2020-02-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200216_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='datetime',
            field=models.DateField(default=111),
            preserve_default=False,
        ),
    ]