# Generated by Django 3.0.3 on 2020-03-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=1000),
        ),
    ]
