# Generated by Django 3.0.3 on 2020-02-16 05:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200131_1240'),
        ('events', '0002_auto_20200213_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=datetime.datetime(2020, 2, 16, 5, 10, 35, 387636, tzinfo=utc), on_delete=models.SET('Deleted'), to='users.RegularUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(default=datetime.datetime(2020, 2, 16, 5, 10, 45, 568409, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='atendees', to='users.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=datetime.datetime(2020, 2, 16, 5, 10, 52, 633642, tzinfo=utc), on_delete=django.db.models.deletion.PROTECT, related_name='organizer', to='users.RegularUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.ForeignKey(default=datetime.datetime(2020, 2, 16, 5, 11, 22, 843965, tzinfo=utc), on_delete=django.db.models.deletion.PROTECT, to='events.Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.date(2020, 2, 16)),
        ),
    ]
