# Generated by Django 3.0.2 on 2020-02-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200216_0037'),
        ('events', '0003_event_datetime'),
    ]

    operations = [
    ]
