# Generated by Django 3.0.3 on 2020-03-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200307_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isRegistered',
            field=models.BooleanField(default=False),
        ),
    ]
