# Generated by Django 3.0.3 on 2020-03-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_isregistered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='isRegistered',
        ),
    ]
